# Generated by Django 5.2.17 on 2026-10-05 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Готово'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('client_name', models.CharField(max_length=120, verbose_name='Клиент')),
                ('client_phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость, ₽')),
                ('prepayment', models.PositiveIntegerField(default=0, verbose_name='Предоплата, ₽')),
                ('note', models.TextField(blank=True, verbose_name='Заметка исполнителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['due_date', 'due_time', '-number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_external_order')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Пункт')),
                ('done', models.BooleanField(default=False, verbose_name='Готово')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='orders.order')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Чек-лист',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Событие')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'История',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='orders/%Y/%m/', verbose_name='Файл')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['position', 'id'],
            },
        ),
    ]
